apiVersion: v1
entries:
  orc:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-05-25T12:01:40.4159145Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 78d93584721167b367a26c6493793ee4482b8334191b8a6a78563e239a9faff1
    home: orc.zaakonline.nl
    icon: orc.zaakonline.nl
    name: orc
    urls:
    - orc-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-25T12:01:40.3982108Z"
