apiVersion: v1
entries:
  orderregistratiecomponent:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2021-06-22T14:49:11.3743551Z"
    description: Het Order Registratie component verzorgt de afhandeling van bestellingen
      met uitzondering van facturatie en betalingen. Het biedt in samenwerking met
      het PDC een multi-tenant en omnichannel oplossing voor het verkopen van producten
      en diensten. Hierbij worden offers (te kopen resources vanuit het PC) toegevoegd
      aan een order, waarbij het Registratie Order Component de geldigheid van de
      aanbieding controleert en een eventuele prijs en betaling berekeningen uitvoert.
    digest: 3b2f7423c8d3d1f2c8dd3bc008f0ca262d4f417b7d69f028b18472fc3c6c3ecb
    home: https://www.conduction.nl
    icon: https://conductionnl.github.io/images/conduction_avatar_blue_on_transparant.svg
    keywords:
    - commonground
    - haven
    - nlx
    - component
    maintainers:
    - email: ruben@conduction.nl
      name: Ruben van der Linde
    - email: info@conduction.nl
      name: Conduction
    name: orderregistratiecomponent
    sources:
    - https://commonground.conduction.nl/
    - https://www.commonground.nl/
    urls:
    - orderregistratiecomponent-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
    apiVersion: v2
    appVersion: 11.10.0
    created: "2021-06-22T14:49:11.3888152Z"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 1.x.x
    description: Chart for PostgreSQL, an object-relational database management system
      (ORDBMS) with an emphasis on extensibility and on standards-compliance.
    digest: eebe8f456cf98d5927a35666d1d899174dc4d3e09f26788033f761527bc90749
    home: https://github.com/bitnami/charts/tree/master/bitnami/postgresql
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-110x117.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - email: containers@bitnami.com
      name: Bitnami
    - email: cedric@desaintmartin.fr
      name: desaintmartin
    name: postgresql
    sources:
    - https://github.com/bitnami/bitnami-docker-postgresql
    - https://www.postgresql.org/
    urls:
    - charts/postgresql-10.1.1.tgz
    version: 10.1.1
generated: "2021-06-22T14:49:11.3609433Z"
